// done
Table lexical_unit {
    id int [pk]
    is_inflected boolean
    is_dialect boolean
    is_mwlu boolean
}

// done (4)
Table lemma {
  id int [pk]
  lemma text [unique]
}

// done
Table dict_entry {
    id int [pk]
    lemma_id int [ref: > lemma.id]
    pos text
}

// done
Table verb_lemma {
    id int [pk, ref: > dict_entry.id]
    present_root text
    past_root text
    is_transitive boolean
}

// left empty
Table verb_transitivity_alternation {
    transitive_id int [ref: > verb_lemma.id]
    intransitive_id int [ref: > verb_lemma.id]
}

// done
Table dialect {
  id int [pk]
  name text
  western boolean
  eastern boolean
}

// done
Table lexical_unit_dialects {
  lexical_unit_id int [ref: > lexical_unit.id]
  dialect_id int [ref: > dialect.id]
}


Table morpheme {
  id int [pk]
  is_prefix boolean
  is_suffix boolean
}

Table prefix_morpheme {
  id int [ref: > morpheme.id]
  is_derivational boolean
}

// done
Table suffix_morpheme {
  id int [ref: > morpheme.id]
  is_person_number boolean
  is_object boolean
}

Table mwlu {
    id int [pk, ref: > lexical_unit.id]
    class text
}

// done
Table form {
  id int [pk, ref: > lexical_unit.id]
  form text
  dict_entry int [ref: > dict_entry.id]
}

// done
Table verb_form {
  form_id int [pk, ref: > form.id]
  person_id text [ref: > person.person_id]
  number_id text [ref: > number.number_id]
  tense_id text [ref: > tense.tense_id]
  mood_id text [ref: > mood.mood_id]
  aspect_id text [ref: > aspect.aspect_id]
  has_aux boolean

  indexes {
    (person_id, number_id, tense_id, mood_id, aspect_id)
  }
}

// done
Table person {
  person_id int [pk]
  value text
}

// done
Table number {
  number_id text [pk]
  value text
}

// done
Table tense {
  tense_id text [pk]
  value text
}

// done
Table mood {
  mood_id text [pk]
  value text
}

// done
Table aspect {
  aspect_id text [pk]
  value text
}

// done 
Table gloss {
  id int [pk]
  lexical_unit_id int [ref: > lexical_unit.id]
  language_id text
  gloss text
}

// // continuation class
// Table continuation_class {
//   id int [pk]
//   name text
// }

// Table lemma_continuation {
//   lemma_id int
//   continuation_id int
// }
